# Generated by Django 4.1.7 on 2023-11-20 16:53

import backend.utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('title', models.CharField(help_text='album title', max_length=50, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
            bases=(models.Model, backend.utils.models.PrintableMixin),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('name', models.CharField(help_text='artist name', max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
            bases=(models.Model, backend.utils.models.PrintableMixin),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('title', models.CharField(help_text='track title', max_length=50, verbose_name='title')),
                ('is_live', models.BooleanField(default=True, help_text='is live', verbose_name='is live')),
                ('album', models.ForeignKey(help_text='album', on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='track.album', verbose_name='album')),
                ('artist', models.ForeignKey(help_text='artist', on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='track.artist', verbose_name='artist')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
            bases=(models.Model, backend.utils.models.PrintableMixin),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(help_text='artist', on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='track.artist', verbose_name='artist'),
        ),
    ]
