[features]
seeds = false
skip-lint = false

[programs.localnet]
genie = "14t9ipmpiRmQpPuizYwenHgp3y8jG5E4sezwDSS5dM7N"

[programs.devnet]
genie = "14t9ipmpiRmQpPuizYwenHgp3y8jG5E4sezwDSS5dM7N"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/devnet.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
