# Generated by Django 4.1.7 on 2023-10-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('accounts', '0001_initial'),
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inboxes', to='blockchain.network'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='sns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inboxes', to='sns.sns'),
        ),
        migrations.AddConstraint(
            model_name='inbox',
            constraint=models.UniqueConstraint(fields=('pub_key', 'network', 'sns'), name='unique (pub_key, network, sns)'),
        ),
    ]
