# Generated by Django 4.1.7 on 2023-11-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='secret_key',
            field=models.CharField(help_text='secret key', max_length=1000, verbose_name='secret key'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='secret_key',
            field=models.CharField(help_text='secret key', max_length=1000, verbose_name='secret key'),
        ),
    ]
