# Generated by Django 4.1.7 on 2023-11-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_inbox_secret_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='secret_key',
            field=models.BinaryField(help_text='secret key', verbose_name='secret key'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='secret_key',
            field=models.BinaryField(help_text='secret key', verbose_name='secret key'),
        ),
    ]
