# Generated by Django 4.1.7 on 2023-11-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_inbox_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='wallet_address',
            field=models.CharField(default='temp', help_text='wallet address', max_length=100, unique=True, verbose_name='wallet address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='wallet_address',
            field=models.CharField(default='temp', help_text='wallet address', max_length=100, unique=True, verbose_name='wallet address'),
            preserve_default=False,
        ),
    ]
