# Generated by Django 4.1.7 on 2023-11-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_inbox_wallet_address_socialaccount_wallet_address'),
        ('accounts', '0005_socialaccount_did_connect_lastfm_and_more'),
    ]

    operations = [
    ]
