# Generated by Django 4.1.7 on 2023-11-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='server',
            name='unique (sns, server)',
        ),
        migrations.AddField(
            model_name='server',
            name='server_id',
            field=models.CharField(default='temp', max_length=100, unique=True, verbose_name='SNS server id'),
            preserve_default=False,
        ),
    ]
