# Generated by Django 4.1.7 on 2023-10-15 18:53

import backend.utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('name', models.CharField(blank=True, help_text='Coin name (ex. Solana, USDCoin ...)', max_length=50, verbose_name='Coin name')),
                ('ticker', models.CharField(blank=True, help_text='Coin ticker (ex. SOL, USDC ...)', max_length=10, null=True, verbose_name='Coin ticker')),
                ('mint_address', models.CharField(help_text='mint address', max_length=100, verbose_name='mint address')),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coin',
            },
            bases=(models.Model, backend.utils.models.PrintableMixin),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('name', models.CharField(help_text='NFT name (ex. NOIS, Sodead ...)', max_length=50, verbose_name='NFT name')),
                ('mint_address', models.CharField(blank=True, help_text='mint address', max_length=100, null=True, verbose_name='mint address')),
            ],
            options={
                'verbose_name': 'NFT Collection',
                'verbose_name_plural': 'NFT Collection',
            },
            bases=(models.Model, backend.utils.models.PrintableMixin),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('name', models.CharField(help_text='Network name (ex. Solana ...)', max_length=50, unique=True, verbose_name='Network name')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Network',
            },
            bases=(models.Model, backend.utils.models.PrintableMixin),
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('name', models.CharField(help_text='NFT name (ex. NOIS #100, ...)', max_length=50, verbose_name='NFT name')),
                ('mint_address', models.CharField(help_text='mint address', max_length=100, verbose_name='mint address')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NFT', to='blockchain.collection')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NFT', to='blockchain.network')),
            ],
            options={
                'verbose_name': 'NFT',
                'verbose_name_plural': 'NFTs',
            },
            bases=(models.Model, backend.utils.models.PrintableMixin),
        ),
        migrations.CreateModel(
            name='NFTTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('tx_hash', models.CharField(help_text='tx hash', max_length=100, unique=True, verbose_name='tx_hash')),
                ('from_inbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_nft_tx', to='accounts.inbox')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_tx_histories', to='blockchain.nft')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_tx_histories', to='sns.server')),
                ('to_inbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_nft_tx', to='accounts.inbox')),
            ],
            options={
                'verbose_name': 'NFT Transaction History',
                'verbose_name_plural': 'NFT Transaction History',
            },
            bases=(models.Model, backend.utils.models.PrintableMixin),
        ),
        migrations.AddField(
            model_name='collection',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_collections', to='blockchain.network'),
        ),
        migrations.CreateModel(
            name='CoinTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at model')),
                ('created_by', models.IntegerField(blank=True, help_text='user creates model', null=True, verbose_name='user creates model')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at model')),
                ('updated_by', models.IntegerField(blank=True, help_text='user updates model', null=True, verbose_name='user updates model')),
                ('is_deleted', models.BooleanField(default=False, help_text='just flag, not delete data actually', verbose_name='Whether model is deleted')),
                ('tx_hash', models.CharField(help_text='tx hash', max_length=100, unique=True, verbose_name='tx_hash')),
                ('amount', models.CharField(default='0', help_text='sent coin amount', max_length=100, verbose_name='coin_amount')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_tx_histories', to='blockchain.coin')),
                ('from_inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_coin_tx', to='accounts.inbox')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_tx_histories', to='sns.server')),
                ('to_inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_coin_tx', to='accounts.inbox')),
            ],
            options={
                'verbose_name': 'Coin Transaction History',
                'verbose_name_plural': 'Coin Transaction History',
            },
            bases=(models.Model, backend.utils.models.PrintableMixin),
        ),
        migrations.AddField(
            model_name='coin',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='blockchain.network'),
        ),
        migrations.AddConstraint(
            model_name='nft',
            constraint=models.UniqueConstraint(fields=('network', 'mint_address'), name='unique nft (network, mint_address)'),
        ),
        migrations.AddConstraint(
            model_name='coin',
            constraint=models.UniqueConstraint(fields=('network', 'mint_address'), name='unique coin (network, mint_address)'),
        ),
    ]
