# Generated by Django 4.1.7 on 2023-10-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_alter_nft_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NFT', to='blockchain.collection'),
        ),
    ]
