# Generated by Django 4.1.7 on 2023-11-24 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_remove_server_unique (sns, server)_server_server_id'),
        ('blockchain', '0003_alter_nft_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransactionhistory',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin_tx_histories', to='sns.server'),
        ),
        migrations.AlterField(
            model_name='nfttransactionhistory',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nft_tx_histories', to='sns.server'),
        ),
    ]
